version: "3"

services:

  test-setup:
    image: swiftly:ubi9-5.8
    build:
      context: ..
      dockerfile: docker/test-yum.dockerfile
      args:
        base_image: "swift:5.8-rhel-ubi9"

  lint:
    image: swiftly:ubi9-5.8

  test:
    image: swiftly:ubi9-5.8
    environment:
      - SWIFTLY_PLATFORM_NAME=ubi9
      - SWIFTLY_PLATFORM_NAME_FULL=ubi9
      - SWIFTLY_PLATFORM_NAME_PRETTY="Red Hat Enterprise Linux 9"

  install-test-setup:
    image: swiftly:ubi9
    build:
      context: ..
      dockerfile: docker/install-test-yum.dockerfile
      args:
        base_image: "redhat/ubi9:latest"

  install-test:
    image: swiftly:ubi9

  shell:
    image: swiftly:ubi9-5.8
