version: "3"

services:

  test-setup:
    image: swiftly:amazonlinux2-5.7
    build:
      context: ..
      dockerfile: docker/test-yum.dockerfile
      args:
        base_image: "swift:5.7-amazonlinux2"

  lint:
    image: swiftly:amazonlinux2-5.7

  test:
    image: swiftly:amazonlinux2-5.7
    environment:
      - SWIFTLY_PLATFORM_NAME=amazonlinux2
      - SWIFTLY_PLATFORM_NAME_FULL=amazonlinux2
      - SWIFTLY_PLATFORM_NAME_PRETTY="Amazon Linux 2"

  install-test-setup:
    image: swiftly:amazonlinux2
    build:
      context: ..
      dockerfile: docker/install-test-amazonlinux2.dockerfile
      args:
        base_image: "amazonlinux:2"

  install-test:
    image: swiftly:amazonlinux2

  shell:
    image: swiftly:amazonlinux2-5.7
